package me.fuel.greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import me.fuel.greendao.FuelData;

import me.fuel.greendao.FuelDataDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig fuelDataDaoConfig;

    private final FuelDataDao fuelDataDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        fuelDataDaoConfig = daoConfigMap.get(FuelDataDao.class).clone();
        fuelDataDaoConfig.initIdentityScope(type);

        fuelDataDao = new FuelDataDao(fuelDataDaoConfig, this);

        registerDao(FuelData.class, fuelDataDao);
    }
    
    public void clear() {
        fuelDataDaoConfig.getIdentityScope().clear();
    }

    public FuelDataDao getFuelDataDao() {
        return fuelDataDao;
    }

}
