package me.fuel.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table t_FuelData.
 */
public class FuelData implements java.io.Serializable{

    private Long id;
    private java.util.Date date;
    private Integer year;
    private Integer month;
    private Integer day;
    private String time;
    private Integer currentMiles;
    private Float unitPrice;
    private Float totalPrice;
    private Float currentFuelCapacity;
    private Float averageFuel;
    private Boolean isFull;
    private Boolean isEmpty;
    private Boolean lastTimeNoRecord;
    private String fuelQuality;
    private String location;
    private String notes;

    public FuelData() {

    }

    public FuelData(Long id) {
        this.id = id;
    }

    public FuelData(Long id, java.util.Date date, Integer year, Integer month, Integer day, String time, Integer currentMiles, Float unitPrice, Float totalPrice, Float currentFuelCapacity, Float averageFuel, Boolean isFull, Boolean isEmpty, Boolean lastTimeNoRecord, String fuelQuality, String location, String notes) {
        this.id = id;
        this.date = date;
        this.year = year;
        this.month = month;
        this.day = day;
        this.time = time;
        this.currentMiles = currentMiles;
        this.unitPrice = unitPrice;
        this.totalPrice = totalPrice;
        this.currentFuelCapacity = currentFuelCapacity;
        this.averageFuel = averageFuel;
        this.isFull = isFull;
        this.isEmpty = isEmpty;
        this.lastTimeNoRecord = lastTimeNoRecord;
        this.fuelQuality = fuelQuality;
        this.location = location;
        this.notes = notes;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public java.util.Date getDate() {
        return date;
    }

    public void setDate(java.util.Date date) {
        this.date = date;
    }

    public Integer getYear() {
        return year;
    }

    public void setYear(Integer year) {
        this.year = year;
    }

    public Integer getMonth() {
        return month;
    }

    public void setMonth(Integer month) {
        this.month = month;
    }

    public Integer getDay() {
        return day;
    }

    public void setDay(Integer day) {
        this.day = day;
    }

    public String getTime() {
        return time;
    }

    public void setTime(String time) {
        this.time = time;
    }

    public Integer getCurrentMiles() {
        return currentMiles;
    }

    public void setCurrentMiles(Integer currentMiles) {
        this.currentMiles = currentMiles;
    }

    public Float getUnitPrice() {
        return unitPrice;
    }

    public void setUnitPrice(Float unitPrice) {
        this.unitPrice = unitPrice;
    }

    public Float getTotalPrice() {
        return totalPrice;
    }

    public void setTotalPrice(Float totalPrice) {
        this.totalPrice = totalPrice;
    }

    public Float getCurrentFuelCapacity() {
        return currentFuelCapacity;
    }

    public void setCurrentFuelCapacity(Float currentFuelCapacity) {
        this.currentFuelCapacity = currentFuelCapacity;
    }

    public Float getAverageFuel() {
        return averageFuel;
    }

    public void setAverageFuel(Float averageFuel) {
        this.averageFuel = averageFuel;
    }

    public Boolean getIsFull() {
        return isFull;
    }

    public void setIsFull(Boolean isFull) {
        this.isFull = isFull;
    }

    public Boolean getIsEmpty() {
        return isEmpty;
    }

    public void setIsEmpty(Boolean isEmpty) {
        this.isEmpty = isEmpty;
    }

    public Boolean getLastTimeNoRecord() {
        return lastTimeNoRecord;
    }

    public void setLastTimeNoRecord(Boolean lastTimeNoRecord) {
        this.lastTimeNoRecord = lastTimeNoRecord;
    }

    public String getFuelQuality() {
        return fuelQuality;
    }

    public void setFuelQuality(String fuelQuality) {
        this.fuelQuality = fuelQuality;
    }

    public String getLocation() {
        return location;
    }

    public void setLocation(String location) {
        this.location = location;
    }

    public String getNotes() {
        return notes;
    }

    public void setNotes(String notes) {
        this.notes = notes;
    }

}
